name: flame_forge2d
description: Forge2D (Box2D) support for the Flame game engine. This uses the forge2d package and provides wrappers and components to be used inside Flame.
version: 0.7.1-rc8
homepage: https://github.com/flame-engine/flame_forge2d

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.24.0"

dependencies:
  flame:
    git:
      url: git://github.com/flame-engine/flame.git
      ref: spydon.follow-vector2-method
      path: packages/flame
  forge2d: ^0.7.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.9.4
